---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: kiran007anil/pcf-docker
    tag: final1

inputs:
  - name: bbr-pipeline-tasks-repo
  - name: binary
  - name: director-backup-bucket


params:
  SKIP_SSL_VALIDATION: false
  OPSMAN_URL:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_KEY:
  OPSMAN_USER_EC2:
  OPSMAN_IP:
  BOSH_USER: 
  BOSH_PASSWORD: 

run:
  path: /bin/sh
  args:
  - -c
  - |
    cd bbr-pipeline-tasks-repo/tasks/bbr-restore-director/
    chmod +x task.sh
    ./task.sh
