skip-ssl-validation: 
opsman-url: 
passphrase:
opsman-username: 
opsman-password: 
opsman-user-ec2:
opsman-ip: 
bosh-address: 
bosh-username: 
bosh-password: 
bosh-client:
bosh-client-secret: 
backup-artifact-bucket: 
storage-region: 
storage-endpoint: 
storage-access-key-id: 
storage-secret-access-key: 
pivnet-api-token: 

